name: fake-config
credentials:
  wml:
    instance_id: ''
    username: 'username'
    password: 'password'
    url: 'url'
  cos:
    access_key_id: 'access_key_id'
    secret_access_key: 'secret_access_key'
    region: us-geo